### ISSUE TITLE
setup local dev instructions

### ISSUE THREAD

**Issue by pixeline** [becodeorg/LOCD#3]
hi @NickBanken could you write down the few steps to quickly setup a local dev environment, as a setup.md file perhaps ?

**Comment by NickBanken** [comment]
Hello @pixeline I have made a pull request with the setup file. If there is something missing/incorrect/not working, feel free to ping me!

**Comment by NickBanken** [comment]
I just closed the pull request, I will re-send it after a fix.

**Comment by pixeline** [comment]
perfect, thanks a lot!
